#!/bin/sh

#
# Copyright (c) 2013-2015 Apple Inc. All Rights Reserved.
#
# IMPORTANT NOTE: This file is licensed only for use on Apple-branded
# computers and is subject to the terms and conditions of the Apple Software
# License Agreement accompanying the package this file is a part of.
# You may not port this file to another platform without Apple's written consent.
#

# moves the source to the target iff it exists

if [ -f $1 ]; then
	echo "moving file " $1 " to " $2;
	/bin/mv -f $1 $2
fi
