'\" t
.\"     Title: CHECKPOINT
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "CHECKPOINT" "7" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
CHECKPOINT \- force a transaction log checkpoint
.\" CHECKPOINT
.SH "SYNOPSIS"
.sp
.nf
CHECKPOINT
.fi
.SH "DESCRIPTION"
.PP
A checkpoint is a point in the transaction log sequence at which all data files have been updated to reflect the information in the log\&. All data files will be flushed to disk\&. Refer to
Section 29.4, \(lqWAL Configuration\(rq, in the documentation
for more details about what happens during a checkpoint\&.
.PP
The
\fBCHECKPOINT\fR
command forces an immediate checkpoint when the command is issued, without waiting for a regular checkpoint scheduled by the system (controlled by the settings in
Section 18.5.2, \(lqCheckpoints\(rq, in the documentation)\&.
\fBCHECKPOINT\fR
is not intended for use during normal operation\&.
.PP
If executed during recovery, the
\fBCHECKPOINT\fR
command will force a restartpoint (see
Section 29.4, \(lqWAL Configuration\(rq, in the documentation) rather than writing a new checkpoint\&.
.PP
Only superusers can call
\fBCHECKPOINT\fR\&.
.SH "COMPATIBILITY"
.PP
The
\fBCHECKPOINT\fR
command is a
PostgreSQL
language extension\&.
