'\" t
.\"     Title: COMMIT PREPARED
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "COMMIT PREPARED" "7" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
COMMIT_PREPARED \- commit a transaction that was earlier prepared for two\-phase commit
.\" COMMIT PREPARED
.SH "SYNOPSIS"
.sp
.nf
COMMIT PREPARED \fItransaction_id\fR
.fi
.SH "DESCRIPTION"
.PP

\fBCOMMIT PREPARED\fR
commits a transaction that is in prepared state\&.
.SH "PARAMETERS"
.PP
\fItransaction_id\fR
.RS 4
The transaction identifier of the transaction that is to be committed\&.
.RE
.SH "NOTES"
.PP
To commit a prepared transaction, you must be either the same user that executed the transaction originally, or a superuser\&. But you do not have to be in the same session that executed the transaction\&.
.PP
This command cannot be executed inside a transaction block\&. The prepared transaction is committed immediately\&.
.PP
All currently available prepared transactions are listed in the
pg_prepared_xacts
system view\&.
.SH "EXAMPLES"
.PP
Commit the transaction identified by the transaction identifier
foobar:
.sp
.if n \{\
.RS 4
.\}
.nf
COMMIT PREPARED \*(Aqfoobar\*(Aq;
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP

\fBCOMMIT PREPARED\fR
is a
PostgreSQL
extension\&. It is intended for use by external transaction management systems, some of which are covered by standards (such as X/Open XA), but the SQL side of those systems is not standardized\&.
.SH "SEE ALSO"
PREPARE TRANSACTION (\fBPREPARE_TRANSACTION\fR(7)), ROLLBACK PREPARED (\fBROLLBACK_PREPARED\fR(7))
