'\" t
.\"     Title: DROP EVENT TRIGGER
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "DROP EVENT TRIGGER" "7" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
DROP_EVENT_TRIGGER \- remove an event trigger
.\" DROP EVENT TRIGGER
.SH "SYNOPSIS"
.sp
.nf
DROP EVENT TRIGGER [ IF EXISTS ] \fIname\fR [ CASCADE | RESTRICT ]
.fi
.SH "DESCRIPTION"
.PP

\fBDROP EVENT TRIGGER\fR
removes an existing event trigger\&. To execute this command, the current user must be the owner of the event trigger\&.
.SH "PARAMETERS"
.PP
IF EXISTS
.RS 4
Do not throw an error if the event trigger does not exist\&. A notice is issued in this case\&.
.RE
.PP
\fIname\fR
.RS 4
The name of the event trigger to remove\&.
.RE
.PP
CASCADE
.RS 4
Automatically drop objects that depend on the trigger\&.
.RE
.PP
RESTRICT
.RS 4
Refuse to drop the trigger if any objects depend on it\&. This is the default\&.
.RE
.SH "EXAMPLES"
.PP
Destroy the trigger
snitch:
.sp
.if n \{\
.RS 4
.\}
.nf
DROP EVENT TRIGGER snitch;
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP
There is no
\fBDROP EVENT TRIGGER\fR
statement in the SQL standard\&.
.SH "SEE ALSO"
CREATE EVENT TRIGGER (\fBCREATE_EVENT_TRIGGER\fR(7)), ALTER EVENT TRIGGER (\fBALTER_EVENT_TRIGGER\fR(7))
