'\" t
.\"     Title: DROP SERVER
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "DROP SERVER" "7" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
DROP_SERVER \- remove a foreign server descriptor
.\" DROP SERVER
.SH "SYNOPSIS"
.sp
.nf
DROP SERVER [ IF EXISTS ] \fIname\fR [ CASCADE | RESTRICT ]
.fi
.SH "DESCRIPTION"
.PP

\fBDROP SERVER\fR
removes an existing foreign server descriptor\&. To execute this command, the current user must be the owner of the server\&.
.SH "PARAMETERS"
.PP
IF EXISTS
.RS 4
Do not throw an error if the server does not exist\&. A notice is issued in this case\&.
.RE
.PP
\fIname\fR
.RS 4
The name of an existing server\&.
.RE
.PP
CASCADE
.RS 4
Automatically drop objects that depend on the server (such as user mappings)\&.
.RE
.PP
RESTRICT
.RS 4
Refuse to drop the server if any objects depend on it\&. This is the default\&.
.RE
.SH "EXAMPLES"
.PP
Drop a server
foo
if it exists:
.sp
.if n \{\
.RS 4
.\}
.nf
DROP SERVER IF EXISTS foo;
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP

\fBDROP SERVER\fR
conforms to ISO/IEC 9075\-9 (SQL/MED)\&. The
IF EXISTS
clause is a
PostgreSQL
extension\&.
.SH "SEE ALSO"
CREATE SERVER (\fBCREATE_SERVER\fR(7)), ALTER SERVER (\fBALTER_SERVER\fR(7))
