'\" t
.\"     Title: DROP DOMAIN
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "DROP DOMAIN" "7" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
DROP_DOMAIN \- remove a domain
.\" DROP DOMAIN
.SH "SYNOPSIS"
.sp
.nf
DROP DOMAIN [ IF EXISTS ] \fIname\fR [, \&.\&.\&.] [ CASCADE | RESTRICT ]
.fi
.SH "DESCRIPTION"
.PP

\fBDROP DOMAIN\fR
removes a domain\&. Only the owner of a domain can remove it\&.
.SH "PARAMETERS"
.PP
IF EXISTS
.RS 4
Do not throw an error if the domain does not exist\&. A notice is issued in this case\&.
.RE
.PP
\fIname\fR
.RS 4
The name (optionally schema\-qualified) of an existing domain\&.
.RE
.PP
CASCADE
.RS 4
Automatically drop objects that depend on the domain (such as table columns)\&.
.RE
.PP
RESTRICT
.RS 4
Refuse to drop the domain if any objects depend on it\&. This is the default\&.
.RE
.SH "EXAMPLES"
.PP
To remove the domain
box:
.sp
.if n \{\
.RS 4
.\}
.nf
DROP DOMAIN box;
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP
This command conforms to the SQL standard, except for the
IF EXISTS
option, which is a
PostgreSQL
extension\&.
.SH "SEE ALSO"
CREATE DOMAIN (\fBCREATE_DOMAIN\fR(7)), ALTER DOMAIN (\fBALTER_DOMAIN\fR(7))
