'\" t
.\"     Title: REASSIGN OWNED
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "REASSIGN OWNED" "7" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
REASSIGN_OWNED \- change the ownership of database objects owned by a database role
.\" REASSIGN OWNED
.SH "SYNOPSIS"
.sp
.nf
REASSIGN OWNED BY \fIold_role\fR [, \&.\&.\&.] TO \fInew_role\fR
.fi
.SH "DESCRIPTION"
.PP

\fBREASSIGN OWNED\fR
instructs the system to change the ownership of database objects owned by one of the old_roles, to new_role\&.
.SH "PARAMETERS"
.PP
\fIold_role\fR
.RS 4
The name of a role\&. The ownership of all the objects within the current database, and of all shared objects (databases, tablespaces), owned by this role will be reassigned to
\fInew_role\fR\&.
.RE
.PP
\fInew_role\fR
.RS 4
The name of the role that will be made the new owner of the affected objects\&.
.RE
.SH "NOTES"
.PP

\fBREASSIGN OWNED\fR
is often used to prepare for the removal of one or more roles\&. Because
\fBREASSIGN OWNED\fR
does not affect objects within other databases, it is usually necessary to execute this command in each database that contains objects owned by a role that is to be removed\&.
.PP

\fBREASSIGN OWNED\fR
requires privileges on both the source role(s) and the target role\&.
.PP
The
DROP OWNED (\fBDROP_OWNED\fR(7))
command is an alternative that drops all the database objects owned by one or more roles\&. Note also that
\fBDROP OWNED\fR
requires privileges only on the source role(s)\&.
.PP
The
\fBREASSIGN OWNED\fR
command does not affect the privileges granted to the old_roles in objects that are not owned by them\&. Use
\fBDROP OWNED\fR
to revoke those privileges\&.
.SH "COMPATIBILITY"
.PP
The
\fBREASSIGN OWNED\fR
statement is a
PostgreSQL
extension\&.
.SH "SEE ALSO"
DROP OWNED (\fBDROP_OWNED\fR(7)), DROP ROLE (\fBDROP_ROLE\fR(7)), ALTER DATABASE (\fBALTER_DATABASE\fR(7))
