#!/usr/bin/env ruby

# This file is automatically generated -- DO NOT EDIT

ENV['PATH'] = '/bin:/usr/bin'

begin
  # Check for Snow Leopard
  os_vers = `/usr/bin/sw_vers -productVersion`.chomp.to_f
  if (os_vers < 10.6)
    raise "Requires Snow Leopard or later"
  end

  # Check shared filesystem
  shared_filesystem = ARGV[0]
  server_uuid = ARGV[1]
  
  if (!shared_filesystem || !server_uuid)
    raise "Usage: art.rb <shared_filesystem> <server_uuid>"
  end
  
  if (!File.exist?(shared_filesystem))
    raise "Shared file system does not exist"
  end
  
  info_path = File.join(shared_filesystem, "pcastserverd.plist")  
  if (!File.exist?(info_path))
    raise "#{info_path} does not exist"
  end

  info = IO.read(info_path)
  if (!info.match(server_uuid))
    raise "#{info_path} does not contain #{server_uuid}"
  end
  
  puts "{ artScore = 1; }"  # Success
rescue => boom
  puts "{ artScore = 0; reason = \"#{boom}\"; }"  # Failure
end
