#!/bin/sh
#
SERVERCTL="/Applications/Server.app/Contents/ServerRoot/usr/sbin/serverctl"
LAUNCHD_KEY="com.apple.serviceproxy"
HTTPD_PATH="/usr/sbin/httpd"
HTTPD_WRAPPER_PATH="/Applications/Server.app/Contents/ServerRoot/usr/sbin/httpd-server-wrapper"
CONFIG_PATH="/Library/Server/Web/Config/Proxy/apache_serviceproxy.conf"
ARGV="$@"
PID_PATH="/var/run/service_proxy.pid"
DESKTOP_APACHE_ENV_PATH="/etc/apache2/env.plist"

check_uid() {
    if [ $UID != 0 ]; then
        echo This operation requires root.
        exit 1
    fi
}

run_serverctl() {
    check_uid
    $SERVERCTL $@ > /dev/null
}

ERROR=0
if [ "x$ARGV" = "x" ] ; then 
    ARGV="-h"
fi

case $ARGV in
    start)
    check_uid
    FOUND=`ps -x | grep "httpd.*$CONFIG_PATH" | grep -v grep | wc -l`
    if [ $FOUND = 0 ] ; then
        rm -df $PID_PATH
    fi
    run_serverctl enable service=$LAUNCHD_KEY
    ERROR=$?
    defaults write "$DESKTOP_APACHE_ENV_PATH" "-D SERVER_APP_HAS_DEFAULT_PORTS" ""
    ;;
stop)
    run_serverctl disable service=$LAUNCHD_KEY
    ERROR=$?
    defaults delete "$DESKTOP_APACHE_ENV_PATH" "-D SERVER_APP_HAS_DEFAULT_PORTS"
    ;;
graceful)
    [ -f $PID_PATH ] && kill -USR1 `cat $PID_PATH`
    launchlist=`launchctl list | grep $LAUNCHD_KEY`
    if [ ! -n "$launchlist" ]; then
        run_serverctl enable service=$LAUNCHD_KEY
        defaults write "$DESKTOP_APACHE_ENV_PATH" "-D SERVER_APP_HAS_DEFAULT_PORTS" ""
    fi
    ;;
restart)
    run_serverctl disable service=$LAUNCHD_KEY
    run_serverctl enable service=$LAUNCHD_KEY
    ERROR=$?
    defaults write "$DESKTOP_APACHE_ENV_PATH" "-D SERVER_APP_HAS_DEFAULT_PORTS" ""
    ;;
configtest)
    # Required env vars normally set by com.apple.serviceproxy.plist
    export MODULE_INSTALL_PATH_PREFIX=""
    export SERVER_INSTALL_PATH_PREFIX=/Applications/Server.app/Contents/ServerRoot
    $HTTPD_WRAPPER_PATH -f $CONFIG_PATH -t
    ERROR=$?
    ;;
status|fullstatus)
    echo Status not available. 
    ;;
*)
    $HTTPD_PATH $ARGV
    ERROR=$?
esac

exit $ERROR

