# encoding: utf-8
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require "rubygems"
Gem::Deprecate.skip = true    # Turn off the deprecation warnings, we got it already!
require "bundler/setup"

require 'rake'
require 'rake/testtask'
require 'rdoc/task'

require 'tasks/rails'
