<?PHP
// -------------------------------------------------------------------------
// Copyright (c) 2015 Apple Inc. All rights reserved.
//
// IMPORTANT NOTE: This file is licensed only for use on Apple-branded
// computers and is subject to the terms and conditions of the Apple Software
// License Agreement accompanying the package this file is a part of.
// You may not port this file to another platform without Apple's written consent.
//-------------------------------------------------------------------------

// Only need the schemas for tables we access

$GLOBALS['gTableSchemas'] = [
  ///////////////
  // Relations //
  ///////////////
  'abstract_users' => [
    'id'                 => 'int',
    'admin_temp_id'      => 'varchar',
    'created_at'         => 'timestamp',
    'updated_at'         => 'timestamp',
    'guid'               => 'varchar',
    'email'              => 'varchar',
    'seen_admin'         => 'boolean',
    'od_node_id'         => 'int',
    'uid'                => 'int',
    'primary_group_id'   => 'int',
    'short_name'         => 'varchar',
    'full_name'          => 'varchar',
    'first_name'         => 'varchar',
    'last_name'          => 'varchar',
    'job_title'          => 'varchar',
    'mobile_phone'       => 'varchar',
    'last_synced'        => 'timestamp',
    'vpp_invite_code'    => 'varchar',
    'vpp_status_ext'     => 'varchar',
  ],
  'auto_join_profiles' => [
    'id'                 => 'int',
    'admin_temp_id'      => 'varchar',
    'created_at'         => 'timestamp',
    'updated_at'         => 'timestamp',
    'name'               => 'varchar',
    'is_wildcard'        => 'boolean',
    'reg_challenge'      => 'varchar'
  ],
  'auto_join_profile_usage' => [
    'id'                   => 'int',
    'created_at'           => 'timestamp',
    'auto_join_profile_id' => 'int',
    'device_id'            => 'int',
    'device_tombstone_id'  => 'int'
  ],
  'certificates' => [
    'id'                 => 'int',
    'created_at'         => 'timestamp',
    'common_name'        => 'varchar',
    'expires_at'         => 'timestamp',
    'certificate'        => 'text',
    'private_key'        => 'text',
    'pk_password'        => 'varchar',
    'fingerprint'        => 'varchar',
    'usage_type'         => 'varchar',
    'dynamic_attributes' => 'hash'
  ],
  'device_enrollment_settings' => [
    'id'                     => 'int',
    'admin_temp_id'          => 'varchar',
    'created_at'             => 'timestamp',
    'updated_at'             => 'timestamp',
    'library_item_id'        => 'int',
    'allow_activation_lock'  => 'varchar',
    'dynamic_attributes'     => 'hash'
  ],
  'device_groups' => [
    'id'                          => 'int',
    'admin_temp_id'               => 'varchar',
    'created_at'                  => 'timestamp',
    'updated_at'                  => 'timestamp',
    'library_item_type'           => 'varchar',
    'name'                        => 'varchar',
    'dep_profile_uuid'            => 'varchar',
    'dep_profile'                 => 'hash'
  ],
  'devices' => [
    'id'                          => 'int',
    'admin_temp_id'               => 'varchar',
    'created_at'                  => 'timestamp',
    'updated_at'                  => 'timestamp',
    'library_item_type'           => 'varchar',
    'DeviceName'                  => 'varchar',
    'ProductName'                 => 'varchar',
    'OSVersion'                   => 'varchar',
    'SerialNumber'                => 'varchar',
    'udid'                        => 'varchar',
    'identifier'                  => 'varchar',
    'mdm_target_type'             => 'varchar',
    'user_id'                     => 'int',
    'active_checkin_token'        => 'varchar',
    'checkin_token_valid_at'      => 'timestamp',
    'pending_checkin_token'       => 'varchar',
    'pending_user_id'             => 'int',
    'supports_vpp'                => 'boolean',
    'vpp_last_invite_requested'   => 'timestamp',
    'vpp_last_invite_delivered'   => 'timestamp',
    'last_checkin_time'           => 'timestamp',
    'last_update_info_time'       => 'timestamp',
    'processing_tasks'            => 'boolean',
    'hp_singleton_tasks'          => 'int',
    'lp_singleton_tasks'          => 'int',
    'nn_singleton_tasks'          => 'int',
    'singleton_task_type'         => 'int',
    'singleton_uuid'              => 'varchar',
    'token'                       => 'varchar',
    'push_magic'                  => 'varchar',
    'push_avg_response_time'      => 'int',
    'push_response_times'         => 'varchar',   // Really integer[]
    'mdm_acl'                     => 'int',
    'IMEI'                        => 'varchar',
    'MEID'                        => 'varchar',
    'IsSupervised'                => 'boolean',
    'BluetoothMAC'                => 'varchar',
    'EthernetMAC'                 => 'varchar',
    'WiFiMAC'                     => 'varchar',
    'DeviceID'                    => 'varchar',
    'airplay_password'            => 'varchar',
    'assigned_dep_profile_uuid'   => 'varchar',
    'dep_profile_uuid'            => 'varchar',
    'dep_profile'                 => 'hash',
    'activation_lock_bypass_code' => 'varchar',
    'last_mdm_refresh_ttl_days'   => 'int',
    'is_dep_device'               => 'boolean'
  ],
  'enterprise_apps' => [
    'id'                    => 'int',
    'admin_temp_id'         => 'varchar',
    'created_at'            => 'timestamp',
    'updated_at'            => 'timestamp',
    'asset_type'            => 'varchar',
    'uuid'                  => 'varchar',
    'name'                  => 'varchar',
    'size_in_kb'            => 'int',
    'metadata_last_updated' => 'timestamp',
    'unique_identifier'     => 'varchar',
    'category'              => 'varchar',
    'version'               => 'varchar',
    'alt_version'           => 'varchar',
    'supported_devices'     => 'int',
    'icon_url'              => 'text'
  ],
  'ebooks' => [
    'id'                    => 'int',
    'admin_temp_id'         => 'varchar',
    'created_at'            => 'timestamp',
    'updated_at'            => 'timestamp',
    'asset_type'            => 'varchar',
    'uuid'                  => 'varchar',
    'name'                  => 'varchar',
    'size_in_kb'            => 'int',
    'metadata_last_updated' => 'timestamp',
    'unique_identifier'     => 'varchar',
    'category'              => 'varchar',
    'version'               => 'varchar',
    'alt_version'           => 'varchar',
    'supported_devices'     => 'int',
    'icon_url'              => 'text'
  ],
  'installed_profiles' => [
    'id'                     => 'int',
    'mdm_target_id'          => 'int',
    'profile_id'             => 'int',
    'mdm_task_id'            => 'int',
    'install_failed_at'      => 'timestamp',
    'last_pushed'            => 'timestamp',
    'identifier'             => 'varchar'
  ],
  'lab_sessions' => [
    'id'                       => 'int',
    'admin_temp_id'            => 'varchar',
    'created_at'               => 'timestamp',
    'updated_at'               => 'timestamp',
    'device_id'                => 'int',
    'user_id'                  => 'int',
    'user_guid'                => 'varchar',
    'last_checkin_time'        => 'timestamp',
    'last_auto_sync_profiles'  => 'timestamp',
    'last_auto_sync_media'     => 'timestamp',
    'last_update_info_time'    => 'timestamp',
    'processing_tasks'         => 'boolean',
    'hp_singleton_tasks'       => 'int',
    'lp_singleton_tasks'       => 'int',
    'nn_singleton_tasks'       => 'int',
    'singleton_task_type'      => 'int',
    'singleton_uuid'           => 'varchar',
    'auth_token'               => 'varcahr',
    'token'                    => 'varchar',
    'push_magic'               => 'varchar',
    'push_avg_response_time'   => 'int',
    'push_response_times'      => 'varchar',   // Really integer[]
    'is_owner'                 => 'boolean',
    'checkin_token_valid_at'   => 'timestamp',
    'last_not_on_console'      => 'boolean',
  ],
  'library_item_tasks' => [
    'id'                     => 'int',
    'admin_temp_id'          => 'varchar',
    'created_at'             => 'timestamp',
    'updated_at'             => 'timestamp',
    'task_type'              => 'varchar',
    'target_class'           => 'varchar',
    'target_id'              => 'int',
    'total_target_count'     => 'int',
    'succeeded_target_count' => 'int',
    'canceled_target_count'  => 'int',
    'failed_target_count'    => 'int',
    'completed_at'           => 'timestamp',
    'succeeded'              => 'int',
  ],
  'library_item_metadata' => [
    'id'                 => 'int',
    'dynamic_attributes' => 'hash',
  ],
  'mdm_tasks' => [
    'id'                         => 'int',
    'library_item_task_id'       => 'int',
    'mdm_target_id'              => 'int',
    'profile_id'                 => 'int',
    'library_item_tombstone_id'  => 'int',
    'internal_task_id'           => 'int',
    'task_type'                  => 'varchar',
    'args'                       => 'varchar',
    'params'                     => 'hash',
    'uuid'                       => 'varchar',
    'skipped'                    => 'boolean',
    'updated_at'                 => 'timestamp',
    'completed_at'               => 'timestamp',
    'succeeded'                  => 'int',
  ],
  'network_lab_sessions' => [
    'id'                      => 'int',
    'admin_temp_id'           => 'varchar',
    'created_at'              => 'timestamp',
    'updated_at'              => 'timestamp',
    'device_id'               => 'int',
    'user_id'                 => 'int',
    'user_guid'               => 'varchar',
    'uuid'                    => 'varchar',
    'last_checkin_time'       => 'timestamp',
    'last_auto_sync_profiles' => 'timestamp',
    'last_auto_sync_media'    => 'timestamp',
    'processing_tasks'        => 'boolean',
    'hp_singleton_tasks'      => 'int',
    'lp_singleton_tasks'      => 'int',
    'nn_singleton_tasks'      => 'int',
    'singleton_task_type'     => 'int',
    'singleton_uuid'          => 'varchar',
    'auth_token'              => 'varcahr',
    'token'                   => 'varchar',
    'push_magic'              => 'varchar',
    'is_owner'                => 'boolean',
    'checkin_token_valid_at'  => 'timestamp',
    'last_not_on_console'     => 'boolean',
  ],
  'od_nodes' => [
    'od_node_id'   => 'int',
    'od_node_name' => 'varchar',
  ],
  'owner_lab_sessions' => [
    'id'                      => 'int',
    'admin_temp_id'           => 'varchar',
    'created_at'              => 'timestamp',
    'updated_at'              => 'timestamp',
    'device_id'               => 'int',
    'user_id'                 => 'int',
    'user_guid'               => 'varchar',
    'uuid'                    => 'varchar',
    'last_checkin_time'       => 'timestamp',
    'last_auto_sync_profiles' => 'timestamp',
    'last_auto_sync_media'    => 'timestamp',
    'processing_tasks'        => 'boolean',
    'hp_singleton_tasks'      => 'int',
    'lp_singleton_tasks'      => 'int',
    'nn_singleton_tasks'      => 'int',
    'singleton_task_type'     => 'int',
    'singleton_uuid'          => 'varchar',
    'auth_token'              => 'varcahr',
    'token'                   => 'varchar',
    'push_magic'              => 'varchar',
    'is_owner'                => 'boolean',
    'checkin_token_valid_at'  => 'timestamp',
    'last_not_on_console'     => 'boolean',
  ],
  'profiles' => [
    'id'                       => 'int',
    'admin_temp_id'            => 'varchar',
    'created_at'               => 'timestamp',
    'updated_at'               => 'timestamp',
    'name'                     => 'varchar',
    'uuid'                     => 'varchar',
    'version'                  => 'int',
    'is_a_la_carte'            => 'boolean',
    'is_from_servermgr'        => 'boolean',
    'is_system_level'          => 'boolean',
    'device_id'                => 'int',
    'device_group_id'          => 'int',
    'user_id'                  => 'int',
    'user_group_id'            => 'int',
    'device_substitution_keys' => 'int',
    'user_substitution_keys'   => 'int',
    'profile_cache'            => 'text',
  ],
  'target_tombstones' => [
    'id'           => 'int',
    'target_name'  => 'varchar',
    'target_extra' => 'varchar',
    'target_class' => 'varchar',
    'target_ident' => 'varchar',
  ],
  'users' => [
    'id'                 => 'int',
    'admin_temp_id'      => 'varchar',
    'created_at'         => 'timestamp',
    'updated_at'         => 'timestamp',
    'guid'               => 'varchar',
    'email'              => 'varchar',
    'seen_admin'         => 'boolean',
    'od_node_id'         => 'int',
    'uid'                => 'int',
    'primary_group_id'   => 'int',
    'short_name'         => 'varchar',
    'full_name'          => 'varchar',
    'first_name'         => 'varchar',
    'last_name'          => 'varchar',
    'job_title'          => 'varchar',
    'mobile_phone'       => 'varchar',
    'last_synced'        => 'timestamp',
  ],
  'view_cloud_devices_cloud_locations' => [
    'device_id'         => 'int',
    'cloud_location_id' => 'int',
  ],
  'vpp_products' => [
    'id'                    => 'int',
    'admin_temp_id'         => 'varchar',
    'created_at'            => 'timestamp',
    'updated_at'            => 'timestamp',
    'asset_type'            => 'varchar',
    'uuid'                  => 'varchar',
    'name'                  => 'varchar',
    'size_in_kb'            => 'int',
    'metadata_last_updated' => 'timestamp',
    'unique_identifier'     => 'varchar',
    'category'              => 'varchar',
    'version'               => 'varchar',
    'alt_version'           => 'varchar',
    'supported_devices'     => 'int',
    'icon_url'              => 'text',
    'adam_id_ext'           => 'int',
    'pricing_param'         => 'varchar',
    'product_type_id'       => 'int',
    'irrevocable'           => 'boolean',
    'license_count'         => 'int',
    'vpp_last_synced'       => 'timestamp',
    'variant'               => 'varchar',
  ],
  'xsan_networks' => [
    'id'                        => 'int',
    'admin_temp_id'             => 'varchar',
    'created_at'                => 'timestamp',
    'updated_at'                => 'timestamp',
    'asset_type'                => 'varchar',
    'uuid'                      => 'varchar',
    'name'                      => 'varchar',
    'size_in_kb'                => 'int',
    'metadata_last_updated'     => 'timestamp',
    'san_config_urls'           => 'array',
    'san_auth_method'           => 'varchar',
    'san_auth_secret'           => 'varchar',
  ],

  ///////////////
  // Functions //
  ///////////////
  'dm_allow_portal_enroll_unenrollment_for_user_id' => [
    'user_pk'   => 'int',
  ],
  'dm_complete_mdm_tasks_for_mdm_target' => [
    'target_id'   => 'int',
    'singleton'   => 'int',
    'succeed'     => 'boolean',
    'canceled'    => 'boolean',
    'error_chain' => 'hash'
  ],
  'dm_create_basic_task_for_library_item' => [
    'target_type'  => 'varchar',
    'target_id'    => 'int',
    'type'         => 'varchar',
    'params'       => 'text'
  ],
  'dm_device_application_lists_updated' => [
    'item_id' => 'int',
  ],
  'dm_device_enrollment_settings_for_user' => [
    'u_id' => 'int'
  ],
  'dm_device_media_lists_updated' => [
    'item_id' => 'int',
  ],
  'dm_device_certificate_list_updated' => [
    'item_id' => 'int',
  ],
  'dm_effective_privileges_for_user_id' => [
    'user_pk'   => 'int',
  ],
  'dm_expanded_privileges_for_user_id' => [
    'user_pk'   => 'int',
  ],
  'dm_mdm_target_blocked_tasks_count' => [
    'target_id'    => 'int',
  ],
  'dm_merge_duplicate_device_rows_and_update' => [
    'd_id'    => 'int',
    'd_udid'  => 'varchar',
    'd_sn'    => 'varchar',
    'd_imei'  => 'varchar',
    'd_meid'  => 'varchar',
    'd_devid' => 'varchar'
  ],
  'dm_update_all_profiles_for_mdm_target' => [
    'target_id' => 'int',
    'is_sync'   => 'boolean'
  ],
];