'\" t
.\"     Title: pg_test_fsync
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "PG_TEST_FSYNC" "1" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pg_test_fsync \- determine fastest wal_sync_method for PostgreSQL
.\" pg_test_fsync
.SH "SYNOPSIS"
.HP \w'\fBpg_test_fsync\fR\ 'u
\fBpg_test_fsync\fR [\fIoption\fR...]
.SH "DESCRIPTION"
.PP

pg_test_fsync
is intended to give you a reasonable idea of what the fastest
wal_sync_method
is on your specific system, as well as supplying diagnostic information in the event of an identified I/O problem\&. However, differences shown by
pg_test_fsync
might not make any significant difference in real database throughput, especially since many database servers are not speed\-limited by their transaction logs\&.
pg_test_fsync
reports average file sync operation time in microseconds for each
wal_sync_method, which can also be used to inform efforts to optimize the value of
commit_delay\&.
.SH "OPTIONS"
.PP

pg_test_fsync
accepts the following command\-line options:
.PP
\fB\-f\fR, \fB\-\-filename\fR
.RS 4
Specifies the file name to write test data in\&. This file should be in the same file system that the
pg_xlog
directory is or will be placed in\&. (pg_xlog
contains the
WAL
files\&.) The default is
pg_test_fsync\&.out
in the current directory\&.
.RE
.PP
\fB\-s\fR, \fB\-\-secs\-per\-test\fR
.RS 4
Specifies the number of seconds for each test\&. The more time per test, the greater the test\*(Aqs accuracy, but the longer it takes to run\&. The default is 5 seconds, which allows the program to complete in under 2 minutes\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Print the
pg_test_fsync
version and exit\&.
.RE
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 4
Show help about
pg_test_fsync
command line arguments, and exit\&.
.RE
.SH "AUTHOR"
.PP
Bruce Momjian
<bruce@momjian\&.us>
.SH "SEE ALSO"
\fBpostgres\fR(1)
