source 'http://rubygems.org'

gem "actionmailer", "4.0.0"
gem "curb", "0.8.4"
gem "json", "1.8.0"
gem "msgpack", "0.5.5"
gem "pg", "0.15.1"
gem "sprockets", "2.10.0"
gem "sqlite3", "1.3.7"
gem "CFPropertyList", "2.2.0"
