#!/usr/bin/env /Applications/Server.app/Contents/ServerRoot/usr/bin/ruby
#require File.dirname(__FILE__) + '/../config/boot'
require_relative '../config/boot'
$LOAD_PATH.unshift "#{RAILTIES_PATH}/builtin/rails_info"
require 'commands/about'
