'\" t
.\"     Title: dblink_is_busy
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "DBLINK_IS_BUSY" "3" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dblink_is_busy \- checks if connection is busy with an async query
.\" dblink_is_busy
.SH "SYNOPSIS"
.sp
.nf
dblink_is_busy(text connname) returns int
.fi
.SH "DESCRIPTION"
.PP

\fBdblink_is_busy\fR
tests whether an async query is in progress\&.
.SH "ARGUMENTS"
.PP
\fIconname\fR
.RS 4
Name of the connection to check\&.
.RE
.SH "RETURN VALUE"
.PP
Returns 1 if connection is busy, 0 if it is not busy\&. If this function returns 0, it is guaranteed that
\fBdblink_get_result\fR
will not block\&.
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
SELECT dblink_is_busy(\*(Aqdtest1\*(Aq);
.fi
.if n \{\
.RE
.\}
