'\" t
.\"     Title: SPI_gettype
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "SPI_GETTYPE" "3" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
SPI_gettype \- return the data type name of the specified column
.\" SPI_gettype
.SH "SYNOPSIS"
.sp
.nf
char * SPI_gettype(TupleDesc \fIrowdesc\fR, int \fIcolnumber\fR)
.fi
.SH "DESCRIPTION"
.PP

\fBSPI_gettype\fR
returns a copy of the data type name of the specified column\&. (You can use
\fBpfree\fR
to release the copy of the name when you don\*(Aqt need it anymore\&.)
.SH "ARGUMENTS"
.PP
TupleDesc \fIrowdesc\fR
.RS 4
input row description
.RE
.PP
int \fIcolnumber\fR
.RS 4
column number (count starts at 1)
.RE
.SH "RETURN VALUE"
.PP
The data type name of the specified column, or
NULL
on error\&.
\fISPI_result\fR
is set to
SPI_ERROR_NOATTRIBUTE
on error\&.
