'\" t
.\"     Title: SPI_finish
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "SPI_FINISH" "3" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
SPI_finish \- disconnect a procedure from the SPI manager
.\" SPI_finish
.SH "SYNOPSIS"
.sp
.nf
int SPI_finish(void)
.fi
.SH "DESCRIPTION"
.PP

\fBSPI_finish\fR
closes an existing connection to the SPI manager\&. You must call this function after completing the SPI operations needed during your procedure\*(Aqs current invocation\&. You do not need to worry about making this happen, however, if you abort the transaction via
elog(ERROR)\&. In that case SPI will clean itself up automatically\&.
.PP
If
\fBSPI_finish\fR
is called without having a valid connection, it will return
SPI_ERROR_UNCONNECTED\&. There is no fundamental problem with this; it means that the SPI manager has nothing to do\&.
.SH "RETURN VALUE"
.PP
SPI_OK_FINISH
.RS 4
if properly disconnected
.RE
.PP
SPI_ERROR_UNCONNECTED
.RS 4
if called from an unconnected procedure
.RE
