'\" t
.\"     Title: SPI_freeplan
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "SPI_FREEPLAN" "3" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
SPI_freeplan \- free a previously saved prepared statement
.\" SPI_freeplan
.SH "SYNOPSIS"
.sp
.nf
int SPI_freeplan(SPIPlanPtr \fIplan\fR)
.fi
.SH "DESCRIPTION"
.PP

\fBSPI_freeplan\fR
releases a prepared statement previously returned by
\fBSPI_prepare\fR
or saved by
\fBSPI_keepplan\fR
or
\fBSPI_saveplan\fR\&.
.SH "ARGUMENTS"
.PP
SPIPlanPtr \fIplan\fR
.RS 4
pointer to statement to free
.RE
.SH "RETURN VALUE"
.PP
0 on success;
SPI_ERROR_ARGUMENT
if
\fIplan\fR
is
NULL
or invalid
