'\" t
.\"     Title: SPI_getargcount
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2014
.\"    Manual: PostgreSQL 9.3.5 Documentation
.\"    Source: PostgreSQL 9.3.5
.\"  Language: English
.\"
.TH "SPI_GETARGCOUNT" "3" "2014" "PostgreSQL 9.3.5" "PostgreSQL 9.3.5 Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
SPI_getargcount \- return the number of arguments needed by a statement prepared by \fBSPI_prepare\fR
.\" SPI_getargcount
.SH "SYNOPSIS"
.sp
.nf
int SPI_getargcount(SPIPlanPtr \fIplan\fR)
.fi
.SH "DESCRIPTION"
.PP

\fBSPI_getargcount\fR
returns the number of arguments needed to execute a statement prepared by
\fBSPI_prepare\fR\&.
.SH "ARGUMENTS"
.PP
SPIPlanPtr \fIplan\fR
.RS 4
prepared statement (returned by
\fBSPI_prepare\fR)
.RE
.SH "RETURN VALUE"
.PP
The count of expected arguments for the
\fIplan\fR\&. If the
\fIplan\fR
is
NULL
or invalid,
\fISPI_result\fR
is set to
SPI_ERROR_ARGUMENT
and \-1 is returned\&.
